// TODO: Change this to get datas from the server
export type SkillCategory = 'frontend' | 'backend' | 'etc';
export type Skill = {
  name: string;
  src: string;
  category: SkillCategory;
  category2: string;
};
export type Skills = Skill[];
export const skills: Skills = [
  {
    name: 'HTML5',
    src: '/images/skills/html5.png',
    category: 'etc',
    category2: 'language',
  },
  {
    name: 'CSS',
    src: '/images/skills/css.png',
    category: 'etc',
    category2: 'language',
  },
  {
    name: 'Javascript',
    src: '/images/skills/javascript.png',
    category: 'etc',
    category2: 'language',
  },
  {
    name: 'PHP',
    src: '/images/skills/php.png',
    category: 'etc',
    category2: 'language',
  },
  {
    name: 'Go Language',
    src: '/images/skills/go_language.png',
    category: 'etc',
    category2: 'language',
  },
  {
    name: 'Java',
    src: '/images/skills/java.png',
    category: 'etc',
    category2: 'language',
  },
  {
    name: 'Python',
    src: '/images/skills/python.png',
    category: 'etc',
    category2: 'language',
  },
  {
    name: 'C#',
    src: '/images/skills/c_sharp.png',
    category: 'etc',
    category2: 'language',
  },
  {
    name: 'Spring',
    src: '/images/skills/spring.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Gnuboard5',
    src: '/images/skills/gnuboard.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'React',
    src: '/images/skills/react.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Next.js',
    src: '/images/skills/nextjs.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Antd',
    src: '/images/skills/antd.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Redux',
    src: '/images/skills/redux.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Toast-ui',
    src: '/images/skills/toast_ui.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Tailwind css',
    src: '/images/skills/tailwind.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Ajax',
    src: '/images/skills/ajax.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'ES6',
    src: '/images/skills/ecma.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Axios',
    src: '/images/skills/axios.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Chartjs',
    src: '/images/skills/chartjs.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Bootstrap',
    src: '/images/skills/bootstrap.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'jQuery',
    src: '/images/skills/jquery.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Bootstrap studio',
    src: '/images/skills/bootstrap_studio.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Apollo',
    src: '/images/skills/apollo.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Graphql',
    src: '/images/skills/graphql.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'React-query',
    src: '/images/skills/react_query.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Rest api',
    src: '/images/skills/rest_api.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Lodash',
    src: '/images/skills/lodash.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Notion-api',
    src: '/images/skills/notion.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Typescript',
    src: '/images/skills/typescript.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Emotion',
    src: '/images/skills/emotion.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'SWR',
    src: '/images/skills/swr.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Storybook',
    src: '/images/skills/storybook.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Jest',
    src: '/images/skills/jest.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'framer-motion',
    src: '/images/skills/framer.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'matter.js',
    src: '/images/skills/matter.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'React Native',
    src: '/images/skills/react.png',
    category: 'frontend',
    category2: 'App_Frontend',
  },
  {
    name: 'Flutter',
    src: '/images/skills/flutter.png',
    category: 'frontend',
    category2: 'App_Frontend',
  },
  {
    name: 'Sequelize',
    src: '/images/skills/sequelize.png',
    category: 'backend',
    category2: 'Backend',
  },
  {
    name: 'Strapi',
    src: '/images/skills/strapi.png',
    category: 'backend',
    category2: 'Backend',
  },
  {
    name: 'Gatsby',
    src: '/images/skills/gatsby.png',
    category: 'backend',
    category2: 'Backend',
  },
  {
    name: 'Node.js',
    src: '/images/skills/nodejs.png',
    category: 'backend',
    category2: 'Backend',
  },

  {
    name: 'Nest.js',
    src: '/images/skills/nestjs.png',
    category: 'backend',
    category2: 'Backend',
  },
  {
    name: 'Knex',
    src: '/images/skills/knex.png',
    category: 'backend',
    category2: 'Backend',
  },
  {
    name: 'Socket.io',
    src: '/images/skills/socket_io.png',
    category: 'backend',
    category2: 'Backend',
  },
  {
    name: 'Elasticsearch',
    src: '/images/skills/elasticsearch.png',
    category: 'backend',
    category2: 'Backend',
  },
  {
    name: 'Prisma',
    src: '/images/skills/prisma.png',
    category: 'backend',
    category2: 'Backend',
  },
  {
    name: 'Swagger',
    src: '/images/skills/swagger.png',
    category: 'backend',
    category2: 'Backend',
  },
  {
    name: 'Firebase',
    src: '/images/skills/firebase.png',
    category: 'backend',
    category2: 'Backend',
  },
  {
    name: 'Typeorm',
    src: '/images/skills/typeorm.png',
    category: 'backend',
    category2: 'Backend',
  },
  {
    name: 'Mongoose',
    src: '/images/skills/mongoose.png',
    category: 'backend',
    category2: 'Backend',
  },
  {
    name: 'Redis',
    src: '/images/skills/redis.png',
    category: 'backend',
    category2: 'Backend',
  },
  {
    name: 'Mariadb',
    src: '/images/skills/mariadb.png',
    category: 'backend',
    category2: 'Database',
  },
  {
    name: 'Mysql',
    src: '/images/skills/mysql.png',
    category: 'backend',
    category2: 'Database',
  },
  {
    name: 'Mssql',
    src: '/images/skills/mssql.png',
    category: 'backend',
    category2: 'Database',
  },
  {
    name: 'Mongodb',
    src: '/images/skills/mongodb.png',
    category: 'backend',
    category2: 'Database',
  },
  {
    name: 'PostgreSQL',
    src: '/images/skills/postgresql.png',
    category: 'backend',
    category2: 'Database',
  },
  {
    name: 'SQLite',
    src: '/images/skills/sqlite.png',
    category: 'backend',
    category2: 'Database',
  },
  {
    name: 'NPM',
    src: '/images/skills/npm.png',
    category: 'etc',
    category2: 'etc',
  },
  {
    name: 'Yarn',
    src: '/images/skills/yarn.png',
    category: 'etc',
    category2: 'etc',
  },
  {
    name: 'Unity',
    src: '/images/skills/unity.png',
    category: 'etc',
    category2: 'etc',
  },
  {
    name: 'Git hub',
    src: '/images/skills/github.png',
    category: 'etc',
    category2: 'etc',
  },
  {
    name: 'Git',
    src: '/images/skills/git.png',
    category: 'etc',
    category2: 'etc',
  },
  {
    name: 'Git lab',
    src: '/images/skills/gitlab.png',
    category: 'etc',
    category2: 'etc',
  },
  {
    name: 'Trello',
    src: '/images/skills/trello.png',
    category: 'etc',
    category2: 'etc',
  },
  {
    name: 'Notion',
    src: '/images/skills/notion.png',
    category: 'etc',
    category2: 'etc',
  },
  {
    name: 'Slack',
    src: '/images/skills/slack.png',
    category: 'etc',
    category2: 'etc',
  },
  {
    name: 'Figma',
    src: '/images/skills/figma.png',
    category: 'etc',
    category2: 'etc',
  },
  {
    name: 'Linux',
    src: '/images/skills/linux.png',
    category: 'etc',
    category2: 'Deploy',
  },
  {
    name: 'AWS EC2',
    src: '/images/skills/aws_ec2.png',
    category: 'etc',
    category2: 'Deploy',
  },
  {
    name: 'Docker',
    src: '/images/skills/docker.png',
    category: 'etc',
    category2: 'Deploy',
  },
  {
    name: 'Docker-compose',
    src: '/images/skills/docker_compose.png',
    category: 'etc',
    category2: 'Deploy',
  },
  {
    name: 'PM2',
    src: '/images/skills/pm2.png',
    category: 'etc',
    category2: 'Deploy',
  },
  {
    name: 'Nginx',
    src: '/images/skills/nginx.png',
    category: 'etc',
    category2: 'Deploy',
  },
];

type Projects = {
  name: string;
  skills: string[];
  date: string;
  description: string;
  detail: string;
  screenshots: string[];
}[];
export const projects: Projects = [
  {
    name: 'hoon-jo',
    skills: ['WEB', 'Front-end', 'Deploy'],
    date: '2023-01-01',
    description:
      '현재 보고있는 포트폴리오에 대한 자세한 개발 과정입니다. 프론트엔드 주력 개발자로서 인터랙티브한 애니메이션들과 다양한 레이아웃들을 사용했습니다. 프로젝트 기획에 대해 가장 섬세하고 깊게 생각한 프로젝트 중 하나입니다.',
    detail: `## 주요 목표
다양한 프로젝트를 바탕으로 나를 어떻게 표현해야할까를 깊게 생각했다. 프론트엔드를 주력으로 하고 있기 때문에 다양한 인터랙션들 보여줘야겠다고 생각 했다. 여태까지 작업해왔던 프로젝트들은 어느정도 기획이나 디자인 틀이 잡혀져 있었지만, 이번 프로젝트에서는 기획부터 배포까지 혼자 작업하며, 나를 표현할 방법과 평범한 포트폴리오를 어떻게 벗어날 것인가에 대해 고민을 가장 많이 해야 했다.
## 담당 (전체)
- 프로젝트 기획, 디자인, 개발, 배포
- Page Transition 및 인터랙션
- 반응형
- Matter.js를 이용한 오브젝트 물리법칙 적용
- Next.js를 통한 Server Side 환경 구축

## 배운점
- Matter.js를 통한 물리법칙 구현으로 Canvas에 대한 지식 및 활용
- 레이아웃 구성능력, 애니메이션 고도화
- 홈페이지 디자인에 대한 넓은 관점이 생김
- SSR에 대한 더 넓은 이해, CSR과 SSR의 내부 구동 동작의 차이점

## 아쉬운점
- 최신 버전인 NEXT 13으로 작업하며 Framer와의 충돌로 깔끔하지 못한 Page Transition

## 핵심 사용 기술
- React
- Typescript
- Next.js (Server Side Rendering)
- Framer Motion
- instagram-api
- Matter.js
- Tailwind CSS
- Vercel
`,
    screenshots: [
      '/images/projects/hoon-jo/1.png',
      '/images/projects/hoon-jo/2.png',
      '/images/projects/hoon-jo/3.png',
      '/images/projects/hoon-jo/4.png',
      '/images/projects/hoon-jo/5.png',
      '/images/projects/hoon-jo/6.png',
      '/images/projects/hoon-jo/7.png',
      '/images/projects/hoon-jo/8.png',
    ],
  },
  {
    name: 'hyundai',
    skills: ['WEB', 'Front-end', 'Back-end', 'Deploy'],
    date: '2023-01-02',
    description: '',
    detail: ``,
    screenshots: [
      '/images/projects/hyundai/1.png',
      '/images/projects/hyundai/2.png',
      '/images/projects/hyundai/3.png',
      '/images/projects/hyundai/4.png',
      '/images/projects/hyundai/5.png',
      '/images/projects/hyundai/6.png',
      '/images/projects/hyundai/7.png',
      '/images/projects/hyundai/8.png',
      '/images/projects/hyundai/9.png',
      '/images/projects/hyundai/10.png',
      '/images/projects/hyundai/11.png',
    ],
  },
  {
    name: 'kisti',
    skills: ['WEB', 'Front-end', 'Back-end', 'Deploy'],
    date: '2023-01-03',
    description: '',
    detail: ``,
    screenshots: [
      '/images/projects/kisti/1.png',
      '/images/projects/kisti/2.png',
      '/images/projects/kisti/3.png',
      '/images/projects/kisti/4.png',
      '/images/projects/kisti/5.png',
      '/images/projects/kisti/6.png',
      '/images/projects/kisti/7.png',
      '/images/projects/kisti/8.png',
      '/images/projects/kisti/9.png',
      '/images/projects/kisti/10.png',
      '/images/projects/kisti/11.png',
      '/images/projects/kisti/12.png',
      '/images/projects/kisti/13.png',
      '/images/projects/kisti/14.png',
      '/images/projects/kisti/15.png',
      '/images/projects/kisti/16.png',
      '/images/projects/kisti/17.png',
      '/images/projects/kisti/18.png',
      '/images/projects/kisti/19.png',
      '/images/projects/kisti/20.png',
      '/images/projects/kisti/21.png',
      '/images/projects/kisti/22.png',
      '/images/projects/kisti/23.png',
      '/images/projects/kisti/24.png',
    ],
  },
  {
    name: 'mcst-portal',
    skills: ['WEB', 'Front-end', 'Back-end', 'Deploy'],
    date: '2023-01-04',
    description: '',
    detail: ``,
    screenshots: [
      '/images/projects/mcst/1.png',
      '/images/projects/mcst/2.png',
      '/images/projects/mcst/3.png',
      '/images/projects/mcst/4.png',
      '/images/projects/mcst/5.png',
      '/images/projects/mcst/6.png',
      '/images/projects/mcst/7.png',
      '/images/projects/mcst/8.png',
      '/images/projects/mcst/9.png',
      '/images/projects/mcst/10.png',
      '/images/projects/mcst/11.png',
      '/images/projects/mcst/12.png',
      '/images/projects/mcst/13.png',
      '/images/projects/mcst/14.png',
      '/images/projects/mcst/15.png',
    ],
  },
  {
    name: 'rittal-admin',
    skills: ['WEB', 'Front-end', 'Back-end'],
    date: '2023-01-04',
    description: '',
    detail: ``,
    screenshots: [
      '/images/projects/rittal-admin/1.png',
      '/images/projects/rittal-admin/2.png',
      '/images/projects/rittal-admin/3.png',
      '/images/projects/rittal-admin/4.png',
      '/images/projects/rittal-admin/5.png',
      '/images/projects/rittal-admin/6.png',
      '/images/projects/rittal-admin/7.png',
      '/images/projects/rittal-admin/8.png',
      '/images/projects/rittal-admin/9.png',
      '/images/projects/rittal-admin/10.png',
    ],
  },
  {
    name: 'ctf',
    skills: ['WEB', 'Front-end'],
    date: '2023-01-01',
    description: '',
    detail: ``,
    screenshots: [
      '/images/projects/ctf/1.png',
      '/images/projects/ctf/2.png',
      '/images/projects/ctf/3.png',
      '/images/projects/ctf/4.png',
      '/images/projects/ctf/5.png',
      '/images/projects/ctf/6.png',
      '/images/projects/ctf/7.png',
      '/images/projects/ctf/8.png',
      '/images/projects/ctf/9.png',
      '/images/projects/ctf/10.png',
      '/images/projects/ctf/11.png',
      '/images/projects/ctf/12.png',
      '/images/projects/ctf/13.png',
      '/images/projects/ctf/14.png',
    ],
  },
  {
    name: 'zipida',
    skills: ['WEB', 'Front-end', 'Back-end', 'Deploy'],
    date: '2023-01-05',
    description: '',
    detail: ``,
    screenshots: [
      '/images/projects/zipida/1.png',
      '/images/projects/zipida/2.png',
      '/images/projects/zipida/3.png',
      '/images/projects/zipida/4.png',
      '/images/projects/zipida/5.png',
      '/images/projects/zipida/6.png',
    ],
  },
  {
    name: 'jspo',
    skills: ['WEB', 'Front-end', 'Back-end', 'Deploy'],
    date: '2023-01-07',
    description: '',
    detail: ``,
    screenshots: [
      '/images/projects/jspo/1.png',
      '/images/projects/jspo/2.png',
      '/images/projects/jspo/3.png',
      '/images/projects/jspo/4.png',
      '/images/projects/jspo/5.png',
      '/images/projects/jspo/6.png',
      '/images/projects/jspo/7.png',
      '/images/projects/jspo/8.png',
      '/images/projects/jspo/9.png',
      '/images/projects/jspo/10.png',
      '/images/projects/jspo/11.png',
      '/images/projects/jspo/12.png',
      '/images/projects/jspo/13.png',
      '/images/projects/jspo/14.png',
      '/images/projects/jspo/15.png',
      '/images/projects/jspo/16.png',
      '/images/projects/jspo/17.png',
    ],
  },
  {
    name: 'rittal',
    skills: ['WEB', 'Front-end', 'Back-end', 'Deploy'],
    date: '2023-01-08',
    description: '',
    detail: ``,
    screenshots: [
      '/images/projects/rittal/1.png',
      '/images/projects/rittal/2.png',
      '/images/projects/rittal/3.png',
      '/images/projects/rittal/4.png',
      '/images/projects/rittal/5.png',
      '/images/projects/rittal/6.png',
      '/images/projects/rittal/7.png',
      '/images/projects/rittal/8.png',
      '/images/projects/rittal/9.png',
      '/images/projects/rittal/10.png',
      '/images/projects/rittal/11.png',
      '/images/projects/rittal/12.png',
      '/images/projects/rittal/13.png',
      '/images/projects/rittal/14.png',
      '/images/projects/rittal/15.png',
    ],
  },
  {
    name: 'gcc',
    skills: ['WEB', 'Front-end'],
    date: '2023-01-09',
    description: '',
    detail: ``,
    screenshots: [
      '/images/projects/gcc/1.png',
      '/images/projects/gcc/2.png',
      '/images/projects/gcc/3.png',
      '/images/projects/gcc/4.png',
      '/images/projects/gcc/5.png',
      '/images/projects/gcc/6.png',
      '/images/projects/gcc/7.png',
      '/images/projects/gcc/8.png',
      '/images/projects/gcc/9.png',
      '/images/projects/gcc/10.png',
      '/images/projects/gcc/11.png',
      '/images/projects/gcc/12.png',
      '/images/projects/gcc/13.png',
      '/images/projects/gcc/14.png',
    ],
  },
  {
    name: 'dugi-dugi',
    skills: ['APP', 'Front-end'],
    date: '2023-01-11',
    description: '',
    detail: ``,
    screenshots: [
      '/images/projects/dugi-dugi/1.png',
      '/images/projects/dugi-dugi/2.png',
      '/images/projects/dugi-dugi/3.png',
      '/images/projects/dugi-dugi/4.png',
      '/images/projects/dugi-dugi/5.png',
      '/images/projects/dugi-dugi/6.png',
      '/images/projects/dugi-dugi/7.png',
      '/images/projects/dugi-dugi/8.png',
      '/images/projects/dugi-dugi/9.png',
      '/images/projects/dugi-dugi/10.png',
      '/images/projects/dugi-dugi/11.png',
    ],
  },
  {
    name: 'reservation',
    skills: ['WEB', 'Front-end'],
    date: '2023-01-13',
    description: '',
    detail: ``,
    screenshots: [
      '/images/projects/reservation/1.png',
      '/images/projects/reservation/2.png',
      '/images/projects/reservation/3.png',
      '/images/projects/reservation/4.png',
      '/images/projects/reservation/5.png',
      '/images/projects/reservation/6.png',
      '/images/projects/reservation/7.png',
    ],
  },
];
