// TODO: Change this to get datas from the server
export type SkillCategory = 'frontend' | 'backend' | 'etc';
export type Skill = { name: string; src: string; category: SkillCategory };
export type Skills = Skill[];
export const skills: Skills = [
  { name: 'HTML5', src: '/images/skills/html5.png', category: 'etc' },
  { name: 'CSS', src: '/images/skills/css.png', category: 'etc' },
  { name: 'Javascript', src: '/images/skills/javascript.png', category: 'etc' },
  { name: 'PHP', src: '/images/skills/php.png', category: 'etc' },
  {
    name: 'Go Language',
    src: '/images/skills/go_language.png',
    category: 'etc',
  },
  { name: 'Java', src: '/images/skills/java.png', category: 'etc' },
  { name: 'Python', src: '/images/skills/python.png', category: 'etc' },
  { name: 'C#', src: '/images/skills/c_sharp.png', category: 'etc' },
  { name: 'Spring', src: '/images/skills/spring.png', category: 'frontend' },
  {
    name: 'Gnuboard5',
    src: '/images/skills/gnuboard.png',
    category: 'frontend',
  },
  { name: 'React', src: '/images/skills/react.png', category: 'frontend' },
  { name: 'Next.js', src: '/images/skills/nextjs.png', category: 'frontend' },
  { name: 'Antd', src: '/images/skills/antd.png', category: 'frontend' },
  { name: 'Redux', src: '/images/skills/redux.png', category: 'frontend' },
  {
    name: 'Toast-ui',
    src: '/images/skills/toast_ui.png',
    category: 'frontend',
  },
  {
    name: 'Tailwind css',
    src: '/images/skills/tailwind.png',
    category: 'frontend',
  },
  { name: 'Ajax', src: '/images/skills/ajax.png', category: 'frontend' },
  { name: 'ES6', src: '/images/skills/ecma.png', category: 'frontend' },
  { name: 'Axios', src: '/images/skills/axios.png', category: 'frontend' },
  { name: 'Chartjs', src: '/images/skills/chartjs.png', category: 'frontend' },
  {
    name: 'Bootstrap',
    src: '/images/skills/bootstrap.png',
    category: 'frontend',
  },
  { name: 'jQuery', src: '/images/skills/jquery.png', category: 'frontend' },
  {
    name: 'Bootstrap studio',
    src: '/images/skills/bootstrap_studio.png',
    category: 'frontend',
  },
  { name: 'Apollo', src: '/images/skills/apollo.png', category: 'frontend' },
  { name: 'Graphql', src: '/images/skills/graphql.png', category: 'frontend' },
  {
    name: 'React-query',
    src: '/images/skills/react_query.png',
    category: 'frontend',
  },
  {
    name: 'Rest api',
    src: '/images/skills/rest_api.png',
    category: 'frontend',
  },
  { name: 'Lodash', src: '/images/skills/lodash.png', category: 'frontend' },
  {
    name: 'Notion-api',
    src: '/images/skills/notion.png',
    category: 'frontend',
  },
  {
    name: 'Typescript',
    src: '/images/skills/typescript.png',
    category: 'frontend',
  },
  { name: 'Emotion', src: '/images/skills/emotion.png', category: 'frontend' },
  { name: 'SWR', src: '/images/skills/swr.png', category: 'frontend' },
  {
    name: 'Storybook',
    src: '/images/skills/storybook.png',
    category: 'frontend',
  },
  { name: 'Jest', src: '/images/skills/jest.png', category: 'frontend' },
  {
    name: 'framer-motion',
    src: '/images/skills/framer.png',
    category: 'frontend',
  },
  { name: 'matter.js', src: '/images/skills/matter.png', category: 'frontend' },
  {
    name: 'React Native',
    src: '/images/skills/react.png',
    category: 'frontend',
  },
  { name: 'Flutter', src: '/images/skills/flutter.png', category: 'frontend' },
  {
    name: 'Sequelize',
    src: '/images/skills/sequelize.png',
    category: 'backend',
  },
  { name: 'Strapi', src: '/images/skills/strapi.png', category: 'backend' },
  { name: 'Gatsby', src: '/images/skills/gatsby.png', category: 'backend' },
  { name: 'Node.js', src: '/images/skills/nodejs.png', category: 'backend' },
  { name: 'Nginx', src: '/images/skills/nginx.png', category: 'backend' },
  { name: 'Nest.js', src: '/images/skills/nestjs.png', category: 'backend' },
  { name: 'Knex', src: '/images/skills/knex.png', category: 'backend' },
  {
    name: 'Socket.io',
    src: '/images/skills/socket_io.png',
    category: 'backend',
  },
  {
    name: 'Elasticsearch',
    src: '/images/skills/elasticsearch.png',
    category: 'backend',
  },
  { name: 'Prisma', src: '/images/skills/prisma.png', category: 'backend' },
  { name: 'Swagger', src: '/images/skills/swagger.png', category: 'backend' },
  { name: 'Firebase', src: '/images/skills/firebase.png', category: 'backend' },
  { name: 'Typeorm', src: '/images/skills/typeorm.png', category: 'backend' },
  { name: 'Mongoose', src: '/images/skills/mongoose.png', category: 'backend' },
  { name: 'Redis', src: '/images/skills/redis.png', category: 'backend' },
  { name: 'Mariadb', src: '/images/skills/mariadb.png', category: 'backend' },
  { name: 'Mysql', src: '/images/skills/mysql.png', category: 'backend' },
  { name: 'Mssql', src: '/images/skills/mssql.png', category: 'backend' },
  { name: 'Mongodb', src: '/images/skills/mongodb.png', category: 'backend' },
  {
    name: 'PostgreSQL',
    src: '/images/skills/postgresql.png',
    category: 'backend',
  },
  { name: 'SQLite', src: '/images/skills/sqlite.png', category: 'backend' },
  { name: 'NPM', src: '/images/skills/npm.png', category: 'etc' },
  { name: 'Yarn', src: '/images/skills/yarn.png', category: 'etc' },
  { name: 'Unity', src: '/images/skills/unity.png', category: 'etc' },
  { name: 'Git hub', src: '/images/skills/github.png', category: 'etc' },
  { name: 'Git', src: '/images/skills/git.png', category: 'etc' },
  { name: 'Git lab', src: '/images/skills/gitlab.png', category: 'etc' },
  { name: 'Trello', src: '/images/skills/trello.png', category: 'etc' },
  { name: 'Notion', src: '/images/skills/notion.png', category: 'etc' },
  { name: 'Slack', src: '/images/skills/slack.png', category: 'etc' },
  { name: 'Figma', src: '/images/skills/figma.png', category: 'etc' },
  { name: 'Linux', src: '/images/skills/linux.png', category: 'etc' },
  { name: 'AWS EC2', src: '/images/skills/aws_ec2.png', category: 'etc' },
  { name: 'Docker', src: '/images/skills/docker.png', category: 'etc' },
  {
    name: 'Docker-compose',
    src: '/images/skills/docker_compose.png',
    category: 'etc',
  },
  { name: 'PM2', src: '/images/skills/pm2.png', category: 'etc' },
];

export const projects = [
  'hoon-jo',
  'hyundai',
  'kisti',
  'mcst-portal',
  'ctf',
  'zipida-ver.2',
  'grida',
  'moj-portal',
  'rittal',
  'gcc',
  'mou-portal',
  'dugi-dugi',
  'zipida-ver.1',
  'reservation',
];
