// TODO: Change this to get datas from the server
export type SkillCategory = 'frontend' | 'backend' | 'etc';
export type Skill = {
  name: string;
  src: string;
  category: SkillCategory;
  category2: string;
};
export type Skills = Skill[];
export const skills: Skills = [
  {
    name: 'HTML5',
    src: '/images/skills/html5.png',
    category: 'etc',
    category2: 'language',
  },
  {
    name: 'CSS',
    src: '/images/skills/css.png',
    category: 'etc',
    category2: 'language',
  },
  {
    name: 'Javascript',
    src: '/images/skills/javascript.png',
    category: 'etc',
    category2: 'language',
  },
  {
    name: 'PHP',
    src: '/images/skills/php.png',
    category: 'etc',
    category2: 'language',
  },
  {
    name: 'Go Language',
    src: '/images/skills/go_language.png',
    category: 'etc',
    category2: 'language',
  },
  {
    name: 'Java',
    src: '/images/skills/java.png',
    category: 'etc',
    category2: 'language',
  },
  {
    name: 'Python',
    src: '/images/skills/python.png',
    category: 'etc',
    category2: 'language',
  },
  {
    name: 'C#',
    src: '/images/skills/c_sharp.png',
    category: 'etc',
    category2: 'language',
  },
  {
    name: 'Spring',
    src: '/images/skills/spring.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Gnuboard5',
    src: '/images/skills/gnuboard.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'React',
    src: '/images/skills/react.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Next.js',
    src: '/images/skills/nextjs.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Antd',
    src: '/images/skills/antd.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Redux',
    src: '/images/skills/redux.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Toast-ui',
    src: '/images/skills/toast_ui.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Tailwind css',
    src: '/images/skills/tailwind.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Ajax',
    src: '/images/skills/ajax.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'ES6',
    src: '/images/skills/ecma.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Axios',
    src: '/images/skills/axios.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Chartjs',
    src: '/images/skills/chartjs.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Bootstrap',
    src: '/images/skills/bootstrap.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'jQuery',
    src: '/images/skills/jquery.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Bootstrap studio',
    src: '/images/skills/bootstrap_studio.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Apollo',
    src: '/images/skills/apollo.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Graphql',
    src: '/images/skills/graphql.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'React-query',
    src: '/images/skills/react_query.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Rest api',
    src: '/images/skills/rest_api.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Lodash',
    src: '/images/skills/lodash.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Notion-api',
    src: '/images/skills/notion.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Typescript',
    src: '/images/skills/typescript.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Emotion',
    src: '/images/skills/emotion.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'SWR',
    src: '/images/skills/swr.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Storybook',
    src: '/images/skills/storybook.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'Jest',
    src: '/images/skills/jest.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'framer-motion',
    src: '/images/skills/framer.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'matter.js',
    src: '/images/skills/matter.png',
    category: 'frontend',
    category2: 'Web_Frontend',
  },
  {
    name: 'React Native',
    src: '/images/skills/react.png',
    category: 'frontend',
    category2: 'App_Frontend',
  },
  {
    name: 'Flutter',
    src: '/images/skills/flutter.png',
    category: 'frontend',
    category2: 'App_Frontend',
  },
  {
    name: 'Sequelize',
    src: '/images/skills/sequelize.png',
    category: 'backend',
    category2: 'Backend',
  },
  {
    name: 'Strapi',
    src: '/images/skills/strapi.png',
    category: 'backend',
    category2: 'Backend',
  },
  {
    name: 'Gatsby',
    src: '/images/skills/gatsby.png',
    category: 'backend',
    category2: 'Backend',
  },
  {
    name: 'Node.js',
    src: '/images/skills/nodejs.png',
    category: 'backend',
    category2: 'Backend',
  },

  {
    name: 'Nest.js',
    src: '/images/skills/nestjs.png',
    category: 'backend',
    category2: 'Backend',
  },
  {
    name: 'Knex',
    src: '/images/skills/knex.png',
    category: 'backend',
    category2: 'Backend',
  },
  {
    name: 'Socket.io',
    src: '/images/skills/socket_io.png',
    category: 'backend',
    category2: 'Backend',
  },
  {
    name: 'Elasticsearch',
    src: '/images/skills/elasticsearch.png',
    category: 'backend',
    category2: 'Backend',
  },
  {
    name: 'Prisma',
    src: '/images/skills/prisma.png',
    category: 'backend',
    category2: 'Backend',
  },
  {
    name: 'Swagger',
    src: '/images/skills/swagger.png',
    category: 'backend',
    category2: 'Backend',
  },
  {
    name: 'Firebase',
    src: '/images/skills/firebase.png',
    category: 'backend',
    category2: 'Backend',
  },
  {
    name: 'Typeorm',
    src: '/images/skills/typeorm.png',
    category: 'backend',
    category2: 'Backend',
  },
  {
    name: 'Mongoose',
    src: '/images/skills/mongoose.png',
    category: 'backend',
    category2: 'Backend',
  },
  {
    name: 'Redis',
    src: '/images/skills/redis.png',
    category: 'backend',
    category2: 'Backend',
  },
  {
    name: 'Mariadb',
    src: '/images/skills/mariadb.png',
    category: 'backend',
    category2: 'Database',
  },
  {
    name: 'Mysql',
    src: '/images/skills/mysql.png',
    category: 'backend',
    category2: 'Database',
  },
  {
    name: 'Mssql',
    src: '/images/skills/mssql.png',
    category: 'backend',
    category2: 'Database',
  },
  {
    name: 'Mongodb',
    src: '/images/skills/mongodb.png',
    category: 'backend',
    category2: 'Database',
  },
  {
    name: 'PostgreSQL',
    src: '/images/skills/postgresql.png',
    category: 'backend',
    category2: 'Database',
  },
  {
    name: 'SQLite',
    src: '/images/skills/sqlite.png',
    category: 'backend',
    category2: 'Database',
  },
  {
    name: 'NPM',
    src: '/images/skills/npm.png',
    category: 'etc',
    category2: 'etc',
  },
  {
    name: 'Yarn',
    src: '/images/skills/yarn.png',
    category: 'etc',
    category2: 'etc',
  },
  {
    name: 'Unity',
    src: '/images/skills/unity.png',
    category: 'etc',
    category2: 'etc',
  },
  {
    name: 'Git hub',
    src: '/images/skills/github.png',
    category: 'etc',
    category2: 'etc',
  },
  {
    name: 'Git',
    src: '/images/skills/git.png',
    category: 'etc',
    category2: 'etc',
  },
  {
    name: 'Git lab',
    src: '/images/skills/gitlab.png',
    category: 'etc',
    category2: 'etc',
  },
  {
    name: 'Trello',
    src: '/images/skills/trello.png',
    category: 'etc',
    category2: 'etc',
  },
  {
    name: 'Notion',
    src: '/images/skills/notion.png',
    category: 'etc',
    category2: 'etc',
  },
  {
    name: 'Slack',
    src: '/images/skills/slack.png',
    category: 'etc',
    category2: 'etc',
  },
  {
    name: 'Figma',
    src: '/images/skills/figma.png',
    category: 'etc',
    category2: 'etc',
  },
  {
    name: 'Linux',
    src: '/images/skills/linux.png',
    category: 'etc',
    category2: 'Deploy',
  },
  {
    name: 'AWS EC2',
    src: '/images/skills/aws_ec2.png',
    category: 'etc',
    category2: 'Deploy',
  },
  {
    name: 'Docker',
    src: '/images/skills/docker.png',
    category: 'etc',
    category2: 'Deploy',
  },
  {
    name: 'Docker-compose',
    src: '/images/skills/docker_compose.png',
    category: 'etc',
    category2: 'Deploy',
  },
  {
    name: 'PM2',
    src: '/images/skills/pm2.png',
    category: 'etc',
    category2: 'Deploy',
  },
  {
    name: 'Nginx',
    src: '/images/skills/nginx.png',
    category: 'etc',
    category2: 'Deploy',
  },
];

export const projects = [
  'hoon-jo',
  'hyundai',
  'kisti',
  'mcst-portal',
  'ctf',
  'zipida-ver.2',
  'grida',
  'moj-portal',
  'rittal',
  'gcc',
  'mou-portal',
  'dugi-dugi',
  'zipida-ver.1',
  'reservation',
];
