export const greetings: string[] = [
  '你好',
  'こんにちは',
  'Guten Tag',
  'Bonjour',
  '안녕하세요',
  'Hello',
  'नमस्ते',
  'Ciao',
  'Olá',
  'Привет',
  'Hola',
  'Merhaba',
  'Halo',
  'Cześć',
  'สวัสดี',
  'سلام ',
  'שלום ',
  'السلام عليكم',
  'Xin chào',
  'Kamusta',
  'Selamat pagi',
  'Hallo',
  'Grüezi',
  'Hej',
  'Hei',
  'Γεια σας',
  'Merħba',
  'Bok',
  'Здраво',
  'Здравейте',
  'Ahoj',
  'Halló',
  'Zdravo',
];
// TODO: Change this to get datas from the server
export type SkillCategory = 'frontend' | 'backend' | 'etc';
export type Skill = { name: string; src: string; category: SkillCategory };
export type Skills = Skill[];
export const skills: Skills = [
  { name: 'HTML5', src: '/skills/html5.png', category: 'etc' },
  { name: 'CSS', src: '/skills/css.png', category: 'etc' },
  { name: 'Javascript', src: '/skills/javascript.png', category: 'etc' },
  { name: 'PHP', src: '/skills/php.png', category: 'etc' },
  {
    name: 'Go Language',
    src: '/skills/go_language.png',
    category: 'etc',
  },
  { name: 'Java', src: '/skills/java.png', category: 'etc' },
  { name: 'Python', src: '/skills/python.png', category: 'etc' },
  { name: 'C#', src: '/skills/c_sharp.png', category: 'etc' },
  { name: 'Spring', src: '/skills/spring.png', category: 'frontend' },
  { name: 'Gnuboard5', src: '/skills/gnuboard.png', category: 'frontend' },
  { name: 'React', src: '/skills/react.png', category: 'frontend' },
  { name: 'Next.js', src: '/skills/nextjs.png', category: 'frontend' },
  { name: 'Antd', src: '/skills/antd.png', category: 'frontend' },
  { name: 'Redux', src: '/skills/redux.png', category: 'frontend' },
  { name: 'Toast-ui', src: '/skills/toast_ui.png', category: 'frontend' },
  { name: 'Tailwind css', src: '/skills/tailwind.png', category: 'frontend' },
  { name: 'Ajax', src: '/skills/ajax.png', category: 'frontend' },
  { name: 'ES6', src: '/skills/ecma.png', category: 'frontend' },
  { name: 'Axios', src: '/skills/axios.png', category: 'frontend' },
  { name: 'Chartjs', src: '/skills/chartjs.png', category: 'frontend' },
  { name: 'Bootstrap', src: '/skills/bootstrap.png', category: 'frontend' },
  { name: 'jQuery', src: '/skills/jquery.png', category: 'frontend' },
  {
    name: 'Bootstrap studio',
    src: '/skills/bootstrap_studio.png',
    category: 'frontend',
  },
  { name: 'Apollo', src: '/skills/apollo.png', category: 'frontend' },
  { name: 'Graphql', src: '/skills/graphql.png', category: 'frontend' },
  {
    name: 'React-query',
    src: '/skills/react_query.png',
    category: 'frontend',
  },
  { name: 'Rest api', src: '/skills/rest_api.png', category: 'frontend' },
  { name: 'Lodash', src: '/skills/lodash.png', category: 'frontend' },
  { name: 'Notion-api', src: '/skills/notion.png', category: 'frontend' },
  { name: 'Typescript', src: '/skills/typescript.png', category: 'frontend' },
  { name: 'Emotion', src: '/skills/emotion.png', category: 'frontend' },
  { name: 'SWR', src: '/skills/swr.png', category: 'frontend' },
  { name: 'Storybook', src: '/skills/storybook.png', category: 'frontend' },
  { name: 'Jest', src: '/skills/jest.png', category: 'frontend' },
  { name: 'framer-motion', src: '/skills/framer.png', category: 'frontend' },
  { name: 'matter.js', src: '/skills/matter.png', category: 'frontend' },
  { name: 'React Native', src: '/skills/react.png', category: 'frontend' },
  { name: 'Flutter', src: '/skills/flutter.png', category: 'frontend' },
  { name: 'Sequelize', src: '/skills/sequelize.png', category: 'backend' },
  { name: 'Strapi', src: '/skills/strapi.png', category: 'backend' },
  { name: 'Gatsby', src: '/skills/gatsby.png', category: 'backend' },
  { name: 'Node.js', src: '/skills/nodejs.png', category: 'backend' },
  { name: 'Nginx', src: '/skills/nginx.png', category: 'backend' },
  { name: 'Nest.js', src: '/skills/nestjs.png', category: 'backend' },
  { name: 'Knex', src: '/skills/knex.png', category: 'backend' },
  { name: 'Socket.io', src: '/skills/socket_io.png', category: 'backend' },
  {
    name: 'Elasticsearch',
    src: '/skills/elasticsearch.png',
    category: 'backend',
  },
  { name: 'Prisma', src: '/skills/prisma.png', category: 'backend' },
  { name: 'Swagger', src: '/skills/swagger.png', category: 'backend' },
  { name: 'Firebase', src: '/skills/firebase.png', category: 'backend' },
  { name: 'Typeorm', src: '/skills/typeorm.png', category: 'backend' },
  { name: 'Mongoose', src: '/skills/mongoose.png', category: 'backend' },
  { name: 'Redis', src: '/skills/redis.png', category: 'backend' },
  { name: 'Mariadb', src: '/skills/mariadb.png', category: 'backend' },
  { name: 'Mysql', src: '/skills/mysql.png', category: 'backend' },
  { name: 'Mssql', src: '/skills/mssql.png', category: 'backend' },
  { name: 'Mongodb', src: '/skills/mongodb.png', category: 'backend' },
  { name: 'PostgreSQL', src: '/skills/postgresql.png', category: 'backend' },
  { name: 'SQLite', src: '/skills/sqlite.png', category: 'backend' },
  { name: 'NPM', src: '/skills/npm.png', category: 'etc' },
  { name: 'Yarn', src: '/skills/yarn.png', category: 'etc' },
  { name: 'Unity', src: '/skills/unity.png', category: 'etc' },
  { name: 'Git hub', src: '/skills/github.png', category: 'etc' },
  { name: 'Git', src: '/skills/git.png', category: 'etc' },
  { name: 'Git lab', src: '/skills/gitlab.png', category: 'etc' },
  { name: 'Trello', src: '/skills/trello.png', category: 'etc' },
  { name: 'Notion', src: '/skills/notion.png', category: 'etc' },
  { name: 'Slack', src: '/skills/slack.png', category: 'etc' },
  { name: 'Figma', src: '/skills/figma.png', category: 'etc' },
  { name: 'Linux', src: '/skills/linux.png', category: 'etc' },
  { name: 'AWS EC2', src: '/skills/aws_ec2.png', category: 'etc' },
  { name: 'Docker', src: '/skills/docker.png', category: 'etc' },
  {
    name: 'Docker-compose',
    src: '/skills/docker_compose.png',
    category: 'etc',
  },
  { name: 'PM2', src: '/skills/pm2.png', category: 'etc' },
];
