import { useQuery } from '@tanstack/react-query';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import useProjects from 'queries/project';
import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useRouter } from 'next/router';

export async function getStaticProps({ locale }: any) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])),
    },
  };
}

const Home: NextPage = (props) => {
  const { t } = useTranslation('common');
  console.log(t('test'));
  const { projects, createProject, patchProject, deleteProject } = useProjects({
    // where: { title: { contains: 'repellendus' } },
  });
  const router = useRouter();

  const onCreate = async () => {
    await createProject({ title: 'test', content: 'test-content' });
  };
  const onUpdate = async () => {
    await patchProject({ id: 216, title: 'test', content: 'test-content' });
  };
  const onDelete = async () => {
    await deleteProject(216);
  };
  const changeLangToEnglish = async () => {
    router.push(router.route, router.asPath, {
      locale: 'en',
    });
  };
  const changeLangToKorean = async () => {
    router.push(router.route, router.asPath, {
      locale: 'ko',
    });
  };

  return (
    <div className={styles.container}>
      <button onClick={onCreate}>Create!</button>
      <button onClick={onUpdate}>Update!</button>
      <button onClick={onDelete}>Delete!</button>
      <button onClick={changeLangToKorean}>to Korean</button>
      <button onClick={changeLangToEnglish}>to English</button>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {t('test')}
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
